// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function windChill(temperature, velocity) {
  var t = temperature;
  var v = velocity;
  return 13.12 + 0.6215 * t - 11.37 * Math.pow(v, 0.16) + 0.3965 * t * Math.pow(v, 0.16);
}

var wc = windChill(5, 20);

console.log("At temperature " + (String(5) + (" degrees C and wind speed " + (String(20) + (" km/hr,\nthe wind chill temperature is " + (String(wc) + "."))))));

var temperature = 5;

var velocity = 20;

exports.windChill = windChill;
exports.temperature = temperature;
exports.velocity = velocity;
exports.wc = wc;
/* wc Not a pure module */
